### ISSUE TITLE
Errors after spotify access.

### ISSUE THREAD

**Issue by jmilay** [Deeplocal/scrubber#6]
What am I doing wrong?  after entering spotify client ID and secret and code I get the following:
Token info saved!
Downloading Songs!
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find ffmpeg
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/processor.js:136:22
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/capabilities.js:123:9
    at wrapper (/home/pi/Projects/scrubber/node_modules/async/dist/async.js:268:20)
    at next (/home/pi/Projects/scrubber/node_modules/async/dist/async.js:4582:24)
    at /home/pi/Projects/scrubber/node_modules/async/dist/async.js:321:20
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/capabilities.js:116:11
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/utils.js:223:16
    at F (/home/pi/Projects/scrubber/node_modules/which/which.js:68:16)
    at E (/home/pi/Projects/scrubber/node_modules/which/which.js:80:29)
    at /home/pi/Projects/scrubber/node_modules/which/which.js:89:16
Emitted 'error' event at:
    at emitEnd (/home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/processor.js:433:16
    at wrapper (/home/pi/Projects/scrubber/node_modules/async/dist/async.js:268:20)
    [... lines matching original stack trace ...]
    at wrapper (/home/pi/Projects/scrubber/node_modules/async/dist/async.js:268:20)
    at next (/home/pi/Projects/scrubber/node_modules/async/dist/async.js:4582:24)
    at /home/pi/Projects/scrubber/node_modules/async/dist/async.js:321:20
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/capabilities.js:519:16
    at /home/pi/Projects/scrubber/node_modules/fluent-ffmpeg/lib/processor.js:136:16

When I touch pin 5 and Ground I get:

pi@raspberrypi:~/Projects/scrubber $ node index
Scrubber is Scrubbing!
Song folder Exists!
There are 1 available
Playing 0 now
1

But NO sound.  Please help!

Thank you!

**Comment by AdnanDL** [comment]
Hey can you refer to [this thread here ](https://github.com/Deeplocal/scrubber/issues/1#issuecomment-612219125)

**Comment by jmilay** [comment]
Thank you.  I had the same issues as taylortabb with no ffmpeg and white noise.  His fixes also solved my issues!
